# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Distribution Registry installation tasks
  when: docker_registry_enabled | bool
  tags:
    - setup-all
    - setup-docker-registry
    - install-all
    - install-docker-registry
  block:
    - name: Validate Distribution Registry configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Distribution Registry
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Distribution Registry uninstallation tasks
  when: not docker_registry_enabled | bool
  tags:
    - setup-all
    - setup-docker-registry
  block:
    - name: Uninstall Distribution Registry
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
