# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of Docker Registry systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ docker_registry_identifier }}-server.service"
  register: docker_registry_service_stat

- name: Uninstall docker_registry systemd services and files
  when: docker_registry_service_stat.stat.exists | bool
  block:
    - name: Ensure Docker Registry systemd services are stopped
      ansible.builtin.service:
        name: "{{ item }}"
        state: stopped
        enabled: false
        daemon_reload: true
      with_items:
        - "{{ docker_registry_identifier }}"
        - "{{ docker_registry_identifier }}-garbage-collect"

    - name: Ensure Docker Registry systemd services do not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ item }}"
        state: absent
      with_items:
        - "{{ docker_registry_identifier }}.service"
        - "{{ docker_registry_identifier }}-garbage-collect.service"
        - "{{ docker_registry_identifier }}-garbage-collect.timer"

    - name: Ensure Docker Registry container network does not exist via community.docker.docker_network
      when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
      community.docker.docker_network:
        name: "{{ docker_registry_container_network }}"
        state: absent

    - name: Ensure Docker Registry container network does not exist via ansible.builtin.command
      when: devture_systemd_docker_base_container_network_creation_method == 'command'
      ansible.builtin.command:
        cmd: >-
          {{ devture_systemd_docker_base_host_command_docker }} network rm
          {{ docker_registry_container_network }}
      register: network_deletion_result
      changed_when: docker_registry_container_network in network_deletion_result.stdout

    - name: Ensure Docker Registry path does not exist
      ansible.builtin.file:
        path: "{{ docker_registry_base_path }}"
        state: absent
